import { Elysia, t } from "elysia";
import * as dotenv from "dotenv";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as runtime from "@prisma/client/runtime/client";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
//#region src/generated/prisma/internal/class.ts
const config = {
	"previewFeatures": [],
	"clientVersion": "7.8.0",
	"engineVersion": "3c6e192761c0362d496ed980de936e2f3cebcd3a",
	"activeProvider": "postgresql",
	"inlineSchema": "generator client {\n  provider   = \"prisma-client\"\n  output     = \"../src/generated/prisma\"\n  engineType = \"client\"\n  runtime    = \"bun\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\nenum AuthProvider {\n  EMAIL  @map(\"email\")\n  GOOGLE @map(\"google\")\n}\n\nenum NotificationType {\n  LIKE    @map(\"like\")\n  COMMENT @map(\"comment\")\n  FOLLOW  @map(\"follow\")\n}\n\n// ─────────────────────────────────────────\n// USERS\n// ─────────────────────────────────────────\nmodel User {\n  id                BigInt       @id @default(autoincrement()) @db.BigInt\n  name              String       @db.VarChar(255)\n  username          String       @unique @db.VarChar(255)\n  email             String       @unique @db.VarChar(255)\n  password          String?      @db.VarChar(255)\n  avatar_url        String?      @db.Text\n  bio               String?      @db.Text\n  provider          AuthProvider @default(EMAIL)\n  provider_id       String?      @db.VarChar(255)\n  email_verified_at DateTime?    @db.Timestamp(6)\n  created_at        DateTime     @default(now()) @db.Timestamp(6)\n  updated_at        DateTime     @updatedAt @db.Timestamp(6)\n\n  // Relations\n  posts               Post[]\n  comments            Comment[]\n  post_likes          PostLike[]\n  notifications       Notification[] @relation(\"NotificationRecipient\")\n  acted_notifications Notification[] @relation(\"NotificationActor\")\n\n  @@map(\"users\")\n}\n\n// ─────────────────────────────────────────\n// POSTS\n// ─────────────────────────────────────────\nmodel Post {\n  id         BigInt   @id @default(autoincrement()) @db.BigInt\n  user_id    BigInt   @db.BigInt\n  content    String   @db.Text\n  image_url  String?  @db.Text\n  created_at DateTime @default(now()) @db.Timestamp(6)\n  updated_at DateTime @updatedAt @db.Timestamp(6)\n\n  // Relations\n  user          User           @relation(fields: [user_id], references: [id], onDelete: Cascade)\n  comments      Comment[]\n  post_likes    PostLike[]\n  notifications Notification[]\n\n  @@index([user_id])\n  @@map(\"posts\")\n}\n\n// ─────────────────────────────────────────\n// POST LIKES\n// ─────────────────────────────────────────\nmodel PostLike {\n  id         BigInt   @id @default(autoincrement()) @db.BigInt\n  post_id    BigInt   @db.BigInt\n  user_id    BigInt   @db.BigInt\n  created_at DateTime @default(now()) @db.Timestamp(6)\n\n  // Relations\n  post Post @relation(fields: [post_id], references: [id], onDelete: Cascade)\n  user User @relation(fields: [user_id], references: [id], onDelete: Cascade)\n\n  @@unique([post_id, user_id]) // Prevent duplicate likes\n  @@index([user_id])\n  @@map(\"post_likes\")\n}\n\n// ─────────────────────────────────────────\n// COMMENTS\n// ─────────────────────────────────────────\nmodel Comment {\n  id                BigInt   @id @default(autoincrement()) @db.BigInt\n  post_id           BigInt   @db.BigInt\n  user_id           BigInt   @db.BigInt\n  parent_comment_id BigInt?  @db.BigInt\n  content           String   @db.Text\n  created_at        DateTime @default(now()) @db.Timestamp(6)\n  updated_at        DateTime @updatedAt @db.Timestamp(6)\n\n  // Relations\n  post           Post           @relation(fields: [post_id], references: [id], onDelete: Cascade)\n  user           User           @relation(fields: [user_id], references: [id], onDelete: Cascade)\n  parent_comment Comment?       @relation(\"CommentReplies\", fields: [parent_comment_id], references: [id], onDelete: SetNull)\n  replies        Comment[]      @relation(\"CommentReplies\")\n  notifications  Notification[]\n\n  @@index([post_id])\n  @@index([user_id])\n  @@index([parent_comment_id])\n  @@map(\"comments\")\n}\n\n// ─────────────────────────────────────────\n// NOTIFICATIONS\n// ─────────────────────────────────────────\nmodel Notification {\n  id         BigInt           @id @default(autoincrement()) @db.BigInt\n  user_id    BigInt           @db.BigInt\n  actor_id   BigInt           @db.BigInt\n  type       NotificationType\n  post_id    BigInt?          @db.BigInt\n  comment_id BigInt?          @db.BigInt\n  is_read    Boolean          @default(false)\n  created_at DateTime         @default(now()) @db.Timestamp(6)\n\n  // Relations\n  user    User     @relation(\"NotificationRecipient\", fields: [user_id], references: [id], onDelete: Cascade)\n  actor   User     @relation(\"NotificationActor\", fields: [actor_id], references: [id], onDelete: Cascade)\n  post    Post?    @relation(fields: [post_id], references: [id], onDelete: SetNull)\n  comment Comment? @relation(fields: [comment_id], references: [id], onDelete: SetNull)\n\n  @@index([user_id])\n  @@index([actor_id])\n  @@index([post_id])\n  @@index([comment_id])\n  @@map(\"notifications\")\n}\n",
	"runtimeDataModel": {
		"models": {},
		"enums": {},
		"types": {}
	},
	"parameterizationSchema": {
		"strings": [],
		"graph": ""
	}
};
config.runtimeDataModel = JSON.parse("{\"models\":{\"User\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"username\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"email\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"password\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"avatar_url\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"bio\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"provider\",\"kind\":\"enum\",\"type\":\"AuthProvider\"},{\"name\":\"provider_id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"email_verified_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updated_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"posts\",\"kind\":\"object\",\"type\":\"Post\",\"relationName\":\"PostToUser\"},{\"name\":\"comments\",\"kind\":\"object\",\"type\":\"Comment\",\"relationName\":\"CommentToUser\"},{\"name\":\"post_likes\",\"kind\":\"object\",\"type\":\"PostLike\",\"relationName\":\"PostLikeToUser\"},{\"name\":\"notifications\",\"kind\":\"object\",\"type\":\"Notification\",\"relationName\":\"NotificationRecipient\"},{\"name\":\"acted_notifications\",\"kind\":\"object\",\"type\":\"Notification\",\"relationName\":\"NotificationActor\"}],\"dbName\":\"users\"},\"Post\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"user_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"content\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"image_url\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updated_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"PostToUser\"},{\"name\":\"comments\",\"kind\":\"object\",\"type\":\"Comment\",\"relationName\":\"CommentToPost\"},{\"name\":\"post_likes\",\"kind\":\"object\",\"type\":\"PostLike\",\"relationName\":\"PostToPostLike\"},{\"name\":\"notifications\",\"kind\":\"object\",\"type\":\"Notification\",\"relationName\":\"NotificationToPost\"}],\"dbName\":\"posts\"},\"PostLike\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"post_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"user_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"post\",\"kind\":\"object\",\"type\":\"Post\",\"relationName\":\"PostToPostLike\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"PostLikeToUser\"}],\"dbName\":\"post_likes\"},\"Comment\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"post_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"user_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"parent_comment_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"content\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updated_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"post\",\"kind\":\"object\",\"type\":\"Post\",\"relationName\":\"CommentToPost\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"CommentToUser\"},{\"name\":\"parent_comment\",\"kind\":\"object\",\"type\":\"Comment\",\"relationName\":\"CommentReplies\"},{\"name\":\"replies\",\"kind\":\"object\",\"type\":\"Comment\",\"relationName\":\"CommentReplies\"},{\"name\":\"notifications\",\"kind\":\"object\",\"type\":\"Notification\",\"relationName\":\"CommentToNotification\"}],\"dbName\":\"comments\"},\"Notification\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"user_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"actor_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"type\",\"kind\":\"enum\",\"type\":\"NotificationType\"},{\"name\":\"post_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"comment_id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"is_read\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"NotificationRecipient\"},{\"name\":\"actor\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"NotificationActor\"},{\"name\":\"post\",\"kind\":\"object\",\"type\":\"Post\",\"relationName\":\"NotificationToPost\"},{\"name\":\"comment\",\"kind\":\"object\",\"type\":\"Comment\",\"relationName\":\"CommentToNotification\"}],\"dbName\":\"notifications\"}},\"enums\":{},\"types\":{}}");
config.parameterizationSchema = {
	strings: JSON.parse("[\"where\",\"orderBy\",\"cursor\",\"user\",\"post\",\"parent_comment\",\"replies\",\"actor\",\"comment\",\"notifications\",\"_count\",\"comments\",\"post_likes\",\"posts\",\"acted_notifications\",\"User.findUnique\",\"User.findUniqueOrThrow\",\"User.findFirst\",\"User.findFirstOrThrow\",\"User.findMany\",\"data\",\"User.createOne\",\"User.createMany\",\"User.createManyAndReturn\",\"User.updateOne\",\"User.updateMany\",\"User.updateManyAndReturn\",\"create\",\"update\",\"User.upsertOne\",\"User.deleteOne\",\"User.deleteMany\",\"having\",\"_avg\",\"_sum\",\"_min\",\"_max\",\"User.groupBy\",\"User.aggregate\",\"Post.findUnique\",\"Post.findUniqueOrThrow\",\"Post.findFirst\",\"Post.findFirstOrThrow\",\"Post.findMany\",\"Post.createOne\",\"Post.createMany\",\"Post.createManyAndReturn\",\"Post.updateOne\",\"Post.updateMany\",\"Post.updateManyAndReturn\",\"Post.upsertOne\",\"Post.deleteOne\",\"Post.deleteMany\",\"Post.groupBy\",\"Post.aggregate\",\"PostLike.findUnique\",\"PostLike.findUniqueOrThrow\",\"PostLike.findFirst\",\"PostLike.findFirstOrThrow\",\"PostLike.findMany\",\"PostLike.createOne\",\"PostLike.createMany\",\"PostLike.createManyAndReturn\",\"PostLike.updateOne\",\"PostLike.updateMany\",\"PostLike.updateManyAndReturn\",\"PostLike.upsertOne\",\"PostLike.deleteOne\",\"PostLike.deleteMany\",\"PostLike.groupBy\",\"PostLike.aggregate\",\"Comment.findUnique\",\"Comment.findUniqueOrThrow\",\"Comment.findFirst\",\"Comment.findFirstOrThrow\",\"Comment.findMany\",\"Comment.createOne\",\"Comment.createMany\",\"Comment.createManyAndReturn\",\"Comment.updateOne\",\"Comment.updateMany\",\"Comment.updateManyAndReturn\",\"Comment.upsertOne\",\"Comment.deleteOne\",\"Comment.deleteMany\",\"Comment.groupBy\",\"Comment.aggregate\",\"Notification.findUnique\",\"Notification.findUniqueOrThrow\",\"Notification.findFirst\",\"Notification.findFirstOrThrow\",\"Notification.findMany\",\"Notification.createOne\",\"Notification.createMany\",\"Notification.createManyAndReturn\",\"Notification.updateOne\",\"Notification.updateMany\",\"Notification.updateManyAndReturn\",\"Notification.upsertOne\",\"Notification.deleteOne\",\"Notification.deleteMany\",\"Notification.groupBy\",\"Notification.aggregate\",\"AND\",\"OR\",\"NOT\",\"id\",\"user_id\",\"actor_id\",\"NotificationType\",\"type\",\"post_id\",\"comment_id\",\"is_read\",\"created_at\",\"equals\",\"in\",\"notIn\",\"lt\",\"lte\",\"gt\",\"gte\",\"not\",\"parent_comment_id\",\"content\",\"updated_at\",\"contains\",\"startsWith\",\"endsWith\",\"image_url\",\"name\",\"username\",\"email\",\"password\",\"avatar_url\",\"bio\",\"AuthProvider\",\"provider\",\"provider_id\",\"email_verified_at\",\"every\",\"some\",\"none\",\"post_id_user_id\",\"is\",\"isNot\",\"connectOrCreate\",\"upsert\",\"createMany\",\"set\",\"disconnect\",\"delete\",\"connect\",\"updateMany\",\"deleteMany\",\"increment\",\"decrement\",\"multiply\",\"divide\"]"),
	graph: "yQM2UBQJAADJAQAgCwAAxwEAIAwAAMgBACANAADGAQAgDgAAyQEAIGcAAL8BADBoAAAnABBpAAC_AQAwagQAAAABckAAxQEAIX1AAMUBACGCAQEAwQEAIYMBAQAAAAGEAQEAAAABhQEBAMIBACGGAQEAwgEAIYcBAQDCAQAhiQEAAMMBiQEiigEBAMIBACGLAUAAxAEAIQEAAAABACANAwAAzQEAIAkAAMkBACALAADHAQAgDAAAyAEAIGcAANUBADBoAAADABBpAADVAQAwagQAwAEAIWsEAMABACFyQADFAQAhfAEAwQEAIX1AAMUBACGBAQEAwgEAIQUDAACMAwAgCQAAigMAIAsAAIgDACAMAACJAwAggQEAANYBACANAwAAzQEAIAkAAMkBACALAADHAQAgDAAAyAEAIGcAANUBADBoAAADABBpAADVAQAwagQAAAABawQAwAEAIXJAAMUBACF8AQDBAQAhfUAAxQEAIYEBAQDCAQAhAwAAAAMAIAEAAAQAMAIAAAUAIA8DAADNAQAgBAAAzAEAIAUAANMBACAGAADHAQAgCQAAyQEAIGcAANQBADBoAAAHABBpAADUAQAwagQAwAEAIWsEAMABACFvBADAAQAhckAAxQEAIXsEANABACF8AQDBAQAhfUAAxQEAIQYDAACMAwAgBAAAiwMAIAUAAI0DACAGAACIAwAgCQAAigMAIHsAANYBACAPAwAAzQEAIAQAAMwBACAFAADTAQAgBgAAxwEAIAkAAMkBACBnAADUAQAwaAAABwAQaQAA1AEAMGoEAAAAAWsEAMABACFvBADAAQAhckAAxQEAIXsEANABACF8AQDBAQAhfUAAxQEAIQMAAAAHACABAAAIADACAAAJACABAAAABwAgAwAAAAcAIAEAAAgAMAIAAAkAIA8DAADNAQAgBAAA0gEAIAcAAM0BACAIAADTAQAgZwAAzgEAMGgAAA0AEGkAAM4BADBqBADAAQAhawQAwAEAIWwEAMABACFuAADPAW4ibwQA0AEAIXAEANABACFxIADRAQAhckAAxQEAIQYDAACMAwAgBAAAiwMAIAcAAIwDACAIAACNAwAgbwAA1gEAIHAAANYBACAPAwAAzQEAIAQAANIBACAHAADNAQAgCAAA0wEAIGcAAM4BADBoAAANABBpAADOAQAwagQAAAABawQAwAEAIWwEAMABACFuAADPAW4ibwQA0AEAIXAEANABACFxIADRAQAhckAAxQEAIQMAAAANACABAAAOADACAAAPACABAAAAAwAgAQAAAAcAIAEAAAAHACABAAAADQAgCQMAAM0BACAEAADMAQAgZwAAywEAMGgAABUAEGkAAMsBADBqBADAAQAhawQAwAEAIW8EAMABACFyQADFAQAhAgMAAIwDACAEAACLAwAgCgMAAM0BACAEAADMAQAgZwAAywEAMGgAABUAEGkAAMsBADBqBAAAAAFrBADAAQAhbwQAwAEAIXJAAMUBACGPAQAAygEAIAMAAAAVACABAAAWADACAAAXACADAAAADQAgAQAADgAwAgAADwAgAQAAAAcAIAEAAAAVACABAAAADQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAVACABAAAWADACAAAXACADAAAADQAgAQAADgAwAgAADwAgAwAAAA0AIAEAAA4AMAIAAA8AIAEAAAADACABAAAABwAgAQAAABUAIAEAAAANACABAAAADQAgAQAAAAEAIBQJAADJAQAgCwAAxwEAIAwAAMgBACANAADGAQAgDgAAyQEAIGcAAL8BADBoAAAnABBpAAC_AQAwagQAwAEAIXJAAMUBACF9QADFAQAhggEBAMEBACGDAQEAwQEAIYQBAQDBAQAhhQEBAMIBACGGAQEAwgEAIYcBAQDCAQAhiQEAAMMBiQEiigEBAMIBACGLAUAAxAEAIQoJAACKAwAgCwAAiAMAIAwAAIkDACANAACHAwAgDgAAigMAIIUBAADWAQAghgEAANYBACCHAQAA1gEAIIoBAADWAQAgiwEAANYBACADAAAAJwAgAQAAKAAwAgAAAQAgAwAAACcAIAEAACgAMAIAAAEAIAMAAAAnACABAAAoADACAAABACARCQAAhQMAIAsAAIMDACAMAACEAwAgDQAAggMAIA4AAIYDACBqBAAAAAFyQAAAAAF9QAAAAAGCAQEAAAABgwEBAAAAAYQBAQAAAAGFAQEAAAABhgEBAAAAAYcBAQAAAAGJAQAAAIkBAooBAQAAAAGLAUAAAAABARQAACwAIAxqBAAAAAFyQAAAAAF9QAAAAAGCAQEAAAABgwEBAAAAAYQBAQAAAAGFAQEAAAABhgEBAAAAAYcBAQAAAAGJAQAAAIkBAooBAQAAAAGLAUAAAAABARQAAC4AMAEUAAAuADARCQAA0AIAIAsAAM4CACAMAADPAgAgDQAAzQIAIA4AANECACBqBADcAQAhckAA3wEAIX1AAN8BACGCAQEA7gEAIYMBAQDuAQAhhAEBAO4BACGFAQEAnwIAIYYBAQCfAgAhhwEBAJ8CACGJAQAAywKJASKKAQEAnwIAIYsBQADMAgAhAgAAAAEAIBQAADEAIAxqBADcAQAhckAA3wEAIX1AAN8BACGCAQEA7gEAIYMBAQDuAQAhhAEBAO4BACGFAQEAnwIAIYYBAQCfAgAhhwEBAJ8CACGJAQAAywKJASKKAQEAnwIAIYsBQADMAgAhAgAAACcAIBQAADMAIAIAAAAnACAUAAAzACADAAAAAQAgGwAALAAgHAAAMQAgAQAAAAEAIAEAAAAnACAKCgAAxgIAICEAAMcCACAiAADKAgAgIwAAyQIAICQAAMgCACCFAQAA1gEAIIYBAADWAQAghwEAANYBACCKAQAA1gEAIIsBAADWAQAgD2cAALgBADBoAAA6ABBpAAC4AQAwagQAnAEAIXJAAKABACF9QACgAQAhggEBALABACGDAQEAsAEAIYQBAQCwAQAhhQEBALUBACGGAQEAtQEAIYcBAQC1AQAhiQEAALkBiQEiigEBALUBACGLAUAAugEAIQMAAAAnACABAAA5ADAgAAA6ACADAAAAJwAgAQAAKAAwAgAAAQAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAKAwAAwgIAIAkAAMUCACALAADDAgAgDAAAxAIAIGoEAAAAAWsEAAAAAXJAAAAAAXwBAAAAAX1AAAAAAYEBAQAAAAEBFAAAQgAgBmoEAAAAAWsEAAAAAXJAAAAAAXwBAAAAAX1AAAAAAYEBAQAAAAEBFAAARAAwARQAAEQAMAoDAACgAgAgCQAAowIAIAsAAKECACAMAACiAgAgagQA3AEAIWsEANwBACFyQADfAQAhfAEA7gEAIX1AAN8BACGBAQEAnwIAIQIAAAAFACAUAABHACAGagQA3AEAIWsEANwBACFyQADfAQAhfAEA7gEAIX1AAN8BACGBAQEAnwIAIQIAAAADACAUAABJACACAAAAAwAgFAAASQAgAwAAAAUAIBsAAEIAIBwAAEcAIAEAAAAFACABAAAAAwAgBgoAAJoCACAhAACbAgAgIgAAngIAICMAAJ0CACAkAACcAgAggQEAANYBACAJZwAAtAEAMGgAAFAAEGkAALQBADBqBACcAQAhawQAnAEAIXJAAKABACF8AQCwAQAhfUAAoAEAIYEBAQC1AQAhAwAAAAMAIAEAAE8AMCAAAFAAIAMAAAADACABAAAEADACAAAFACABAAAAFwAgAQAAABcAIAMAAAAVACABAAAWADACAAAXACADAAAAFQAgAQAAFgAwAgAAFwAgAwAAABUAIAEAABYAMAIAABcAIAYDAACZAgAgBAAAmAIAIGoEAAAAAWsEAAAAAW8EAAAAAXJAAAAAAQEUAABYACAEagQAAAABawQAAAABbwQAAAABckAAAAABARQAAFoAMAEUAABaADAGAwAAlwIAIAQAAJYCACBqBADcAQAhawQA3AEAIW8EANwBACFyQADfAQAhAgAAABcAIBQAAF0AIARqBADcAQAhawQA3AEAIW8EANwBACFyQADfAQAhAgAAABUAIBQAAF8AIAIAAAAVACAUAABfACADAAAAFwAgGwAAWAAgHAAAXQAgAQAAABcAIAEAAAAVACAFCgAAkQIAICEAAJICACAiAACVAgAgIwAAlAIAICQAAJMCACAHZwAAswEAMGgAAGYAEGkAALMBADBqBACcAQAhawQAnAEAIW8EAJwBACFyQACgAQAhAwAAABUAIAEAAGUAMCAAAGYAIAMAAAAVACABAAAWADACAAAXACABAAAACQAgAQAAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAwDAACNAgAgBAAAjAIAIAUAAJACACAGAACOAgAgCQAAjwIAIGoEAAAAAWsEAAAAAW8EAAAAAXJAAAAAAXsEAAAAAXwBAAAAAX1AAAAAAQEUAABuACAHagQAAAABawQAAAABbwQAAAABckAAAAABewQAAAABfAEAAAABfUAAAAABARQAAHAAMAEUAABwADABAAAABwAgDAMAAPABACAEAADvAQAgBQAA8QEAIAYAAPIBACAJAADzAQAgagQA3AEAIWsEANwBACFvBADcAQAhckAA3wEAIXsEAOABACF8AQDuAQAhfUAA3wEAIQIAAAAJACAUAAB0ACAHagQA3AEAIWsEANwBACFvBADcAQAhckAA3wEAIXsEAOABACF8AQDuAQAhfUAA3wEAIQIAAAAHACAUAAB2ACACAAAABwAgFAAAdgAgAQAAAAcAIAMAAAAJACAbAABuACAcAAB0ACABAAAACQAgAQAAAAcAIAYKAADpAQAgIQAA6gEAICIAAO0BACAjAADsAQAgJAAA6wEAIHsAANYBACAKZwAArwEAMGgAAH4AEGkAAK8BADBqBACcAQAhawQAnAEAIW8EAJwBACFyQACgAQAhewQAngEAIXwBALABACF9QACgAQAhAwAAAAcAIAEAAH0AMCAAAH4AIAMAAAAHACABAAAIADACAAAJACABAAAADwAgAQAAAA8AIAMAAAANACABAAAOADACAAAPACADAAAADQAgAQAADgAwAgAADwAgAwAAAA0AIAEAAA4AMAIAAA8AIAwDAADlAQAgBAAA5wEAIAcAAOYBACAIAADoAQAgagQAAAABawQAAAABbAQAAAABbgAAAG4CbwQAAAABcAQAAAABcSAAAAABckAAAAABARQAAIYBACAIagQAAAABawQAAAABbAQAAAABbgAAAG4CbwQAAAABcAQAAAABcSAAAAABckAAAAABARQAAIgBADABFAAAiAEAMAEAAAADACABAAAABwAgDAMAAOEBACAEAADjAQAgBwAA4gEAIAgAAOQBACBqBADcAQAhawQA3AEAIWwEANwBACFuAADdAW4ibwQA4AEAIXAEAOABACFxIADeAQAhckAA3wEAIQIAAAAPACAUAACNAQAgCGoEANwBACFrBADcAQAhbAQA3AEAIW4AAN0BbiJvBADgAQAhcAQA4AEAIXEgAN4BACFyQADfAQAhAgAAAA0AIBQAAI8BACACAAAADQAgFAAAjwEAIAEAAAADACABAAAABwAgAwAAAA8AIBsAAIYBACAcAACNAQAgAQAAAA8AIAEAAAANACAHCgAA1wEAICEAANgBACAiAADbAQAgIwAA2gEAICQAANkBACBvAADWAQAgcAAA1gEAIAtnAACbAQAwaAAAmAEAEGkAAJsBADBqBACcAQAhawQAnAEAIWwEAJwBACFuAACdAW4ibwQAngEAIXAEAJ4BACFxIACfAQAhckAAoAEAIQMAAAANACABAACXAQAwIAAAmAEAIAMAAAANACABAAAOADACAAAPACALZwAAmwEAMGgAAJgBABBpAACbAQAwagQAnAEAIWsEAJwBACFsBACcAQAhbgAAnQFuIm8EAJ4BACFwBACeAQAhcSAAnwEAIXJAAKABACENCgAAogEAICEAAK0BACAiAACuAQAgIwAArgEAICQAAK4BACBzBAAAAAF0BAAAAAR1BAAAAAR2BAAAAAF3BAAAAAF4BAAAAAF5BAAAAAF6BACsAQAhBwoAAKIBACAjAACrAQAgJAAAqwEAIHMAAABuAnQAAABuCHUAAABuCHoAAKoBbiINCgAApwEAICEAAKgBACAiAACpAQAgIwAAqQEAICQAAKkBACBzBAAAAAF0BAAAAAV1BAAAAAV2BAAAAAF3BAAAAAF4BAAAAAF5BAAAAAF6BACmAQAhBQoAAKIBACAjAAClAQAgJAAApQEAIHMgAAAAAXogAKQBACELCgAAogEAICMAAKMBACAkAACjAQAgc0AAAAABdEAAAAAEdUAAAAAEdkAAAAABd0AAAAABeEAAAAABeUAAAAABekAAoQEAIQsKAACiAQAgIwAAowEAICQAAKMBACBzQAAAAAF0QAAAAAR1QAAAAAR2QAAAAAF3QAAAAAF4QAAAAAF5QAAAAAF6QAChAQAhCHMCAAAAAXQCAAAABHUCAAAABHYCAAAAAXcCAAAAAXgCAAAAAXkCAAAAAXoCAKIBACEIc0AAAAABdEAAAAAEdUAAAAAEdkAAAAABd0AAAAABeEAAAAABeUAAAAABekAAowEAIQUKAACiAQAgIwAApQEAICQAAKUBACBzIAAAAAF6IACkAQAhAnMgAAAAAXogAKUBACENCgAApwEAICEAAKgBACAiAACpAQAgIwAAqQEAICQAAKkBACBzBAAAAAF0BAAAAAV1BAAAAAV2BAAAAAF3BAAAAAF4BAAAAAF5BAAAAAF6BACmAQAhCHMCAAAAAXQCAAAABXUCAAAABXYCAAAAAXcCAAAAAXgCAAAAAXkCAAAAAXoCAKcBACEIcwgAAAABdAgAAAAFdQgAAAAFdggAAAABdwgAAAABeAgAAAABeQgAAAABeggAqAEAIQhzBAAAAAF0BAAAAAV1BAAAAAV2BAAAAAF3BAAAAAF4BAAAAAF5BAAAAAF6BACpAQAhBwoAAKIBACAjAACrAQAgJAAAqwEAIHMAAABuAnQAAABuCHUAAABuCHoAAKoBbiIEcwAAAG4CdAAAAG4IdQAAAG4IegAAqwFuIg0KAACiAQAgIQAArQEAICIAAK4BACAjAACuAQAgJAAArgEAIHMEAAAAAXQEAAAABHUEAAAABHYEAAAAAXcEAAAAAXgEAAAAAXkEAAAAAXoEAKwBACEIcwgAAAABdAgAAAAEdQgAAAAEdggAAAABdwgAAAABeAgAAAABeQgAAAABeggArQEAIQhzBAAAAAF0BAAAAAR1BAAAAAR2BAAAAAF3BAAAAAF4BAAAAAF5BAAAAAF6BACuAQAhCmcAAK8BADBoAAB-ABBpAACvAQAwagQAnAEAIWsEAJwBACFvBACcAQAhckAAoAEAIXsEAJ4BACF8AQCwAQAhfUAAoAEAIQ4KAACiAQAgIwAAsgEAICQAALIBACBzAQAAAAF0AQAAAAR1AQAAAAR2AQAAAAF3AQAAAAF4AQAAAAF5AQAAAAF6AQCxAQAhfgEAAAABfwEAAAABgAEBAAAAAQ4KAACiAQAgIwAAsgEAICQAALIBACBzAQAAAAF0AQAAAAR1AQAAAAR2AQAAAAF3AQAAAAF4AQAAAAF5AQAAAAF6AQCxAQAhfgEAAAABfwEAAAABgAEBAAAAAQtzAQAAAAF0AQAAAAR1AQAAAAR2AQAAAAF3AQAAAAF4AQAAAAF5AQAAAAF6AQCyAQAhfgEAAAABfwEAAAABgAEBAAAAAQdnAACzAQAwaAAAZgAQaQAAswEAMGoEAJwBACFrBACcAQAhbwQAnAEAIXJAAKABACEJZwAAtAEAMGgAAFAAEGkAALQBADBqBACcAQAhawQAnAEAIXJAAKABACF8AQCwAQAhfUAAoAEAIYEBAQC1AQAhDgoAAKcBACAjAAC3AQAgJAAAtwEAIHMBAAAAAXQBAAAABXUBAAAABXYBAAAAAXcBAAAAAXgBAAAAAXkBAAAAAXoBALYBACF-AQAAAAF_AQAAAAGAAQEAAAABDgoAAKcBACAjAAC3AQAgJAAAtwEAIHMBAAAAAXQBAAAABXUBAAAABXYBAAAAAXcBAAAAAXgBAAAAAXkBAAAAAXoBALYBACF-AQAAAAF_AQAAAAGAAQEAAAABC3MBAAAAAXQBAAAABXUBAAAABXYBAAAAAXcBAAAAAXgBAAAAAXkBAAAAAXoBALcBACF-AQAAAAF_AQAAAAGAAQEAAAABD2cAALgBADBoAAA6ABBpAAC4AQAwagQAnAEAIXJAAKABACF9QACgAQAhggEBALABACGDAQEAsAEAIYQBAQCwAQAhhQEBALUBACGGAQEAtQEAIYcBAQC1AQAhiQEAALkBiQEiigEBALUBACGLAUAAugEAIQcKAACiAQAgIwAAvgEAICQAAL4BACBzAAAAiQECdAAAAIkBCHUAAACJAQh6AAC9AYkBIgsKAACnAQAgIwAAvAEAICQAALwBACBzQAAAAAF0QAAAAAV1QAAAAAV2QAAAAAF3QAAAAAF4QAAAAAF5QAAAAAF6QAC7AQAhCwoAAKcBACAjAAC8AQAgJAAAvAEAIHNAAAAAAXRAAAAABXVAAAAABXZAAAAAAXdAAAAAAXhAAAAAAXlAAAAAAXpAALsBACEIc0AAAAABdEAAAAAFdUAAAAAFdkAAAAABd0AAAAABeEAAAAABeUAAAAABekAAvAEAIQcKAACiAQAgIwAAvgEAICQAAL4BACBzAAAAiQECdAAAAIkBCHUAAACJAQh6AAC9AYkBIgRzAAAAiQECdAAAAIkBCHUAAACJAQh6AAC-AYkBIhQJAADJAQAgCwAAxwEAIAwAAMgBACANAADGAQAgDgAAyQEAIGcAAL8BADBoAAAnABBpAAC_AQAwagQAwAEAIXJAAMUBACF9QADFAQAhggEBAMEBACGDAQEAwQEAIYQBAQDBAQAhhQEBAMIBACGGAQEAwgEAIYcBAQDCAQAhiQEAAMMBiQEiigEBAMIBACGLAUAAxAEAIQhzBAAAAAF0BAAAAAR1BAAAAAR2BAAAAAF3BAAAAAF4BAAAAAF5BAAAAAF6BACuAQAhC3MBAAAAAXQBAAAABHUBAAAABHYBAAAAAXcBAAAAAXgBAAAAAXkBAAAAAXoBALIBACF-AQAAAAF_AQAAAAGAAQEAAAABC3MBAAAAAXQBAAAABXUBAAAABXYBAAAAAXcBAAAAAXgBAAAAAXkBAAAAAXoBALcBACF-AQAAAAF_AQAAAAGAAQEAAAABBHMAAACJAQJ0AAAAiQEIdQAAAIkBCHoAAL4BiQEiCHNAAAAAAXRAAAAABXVAAAAABXZAAAAAAXdAAAAAAXhAAAAAAXlAAAAAAXpAALwBACEIc0AAAAABdEAAAAAEdUAAAAAEdkAAAAABd0AAAAABeEAAAAABeUAAAAABekAAowEAIQOMAQAAAwAgjQEAAAMAII4BAAADACADjAEAAAcAII0BAAAHACCOAQAABwAgA4wBAAAVACCNAQAAFQAgjgEAABUAIAOMAQAADQAgjQEAAA0AII4BAAANACACawQAAAABbwQAAAABCQMAAM0BACAEAADMAQAgZwAAywEAMGgAABUAEGkAAMsBADBqBADAAQAhawQAwAEAIW8EAMABACFyQADFAQAhDwMAAM0BACAJAADJAQAgCwAAxwEAIAwAAMgBACBnAADVAQAwaAAAAwAQaQAA1QEAMGoEAMABACFrBADAAQAhckAAxQEAIXwBAMEBACF9QADFAQAhgQEBAMIBACGQAQAAAwAgkQEAAAMAIBYJAADJAQAgCwAAxwEAIAwAAMgBACANAADGAQAgDgAAyQEAIGcAAL8BADBoAAAnABBpAAC_AQAwagQAwAEAIXJAAMUBACF9QADFAQAhggEBAMEBACGDAQEAwQEAIYQBAQDBAQAhhQEBAMIBACGGAQEAwgEAIYcBAQDCAQAhiQEAAMMBiQEiigEBAMIBACGLAUAAxAEAIZABAAAnACCRAQAAJwAgDwMAAM0BACAEAADSAQAgBwAAzQEAIAgAANMBACBnAADOAQAwaAAADQAQaQAAzgEAMGoEAMABACFrBADAAQAhbAQAwAEAIW4AAM8BbiJvBADQAQAhcAQA0AEAIXEgANEBACFyQADFAQAhBHMAAABuAnQAAABuCHUAAABuCHoAAKsBbiIIcwQAAAABdAQAAAAFdQQAAAAFdgQAAAABdwQAAAABeAQAAAABeQQAAAABegQAqQEAIQJzIAAAAAF6IAClAQAhDwMAAM0BACAJAADJAQAgCwAAxwEAIAwAAMgBACBnAADVAQAwaAAAAwAQaQAA1QEAMGoEAMABACFrBADAAQAhckAAxQEAIXwBAMEBACF9QADFAQAhgQEBAMIBACGQAQAAAwAgkQEAAAMAIBEDAADNAQAgBAAAzAEAIAUAANMBACAGAADHAQAgCQAAyQEAIGcAANQBADBoAAAHABBpAADUAQAwagQAwAEAIWsEAMABACFvBADAAQAhckAAxQEAIXsEANABACF8AQDBAQAhfUAAxQEAIZABAAAHACCRAQAABwAgDwMAAM0BACAEAADMAQAgBQAA0wEAIAYAAMcBACAJAADJAQAgZwAA1AEAMGgAAAcAEGkAANQBADBqBADAAQAhawQAwAEAIW8EAMABACFyQADFAQAhewQA0AEAIXwBAMEBACF9QADFAQAhDQMAAM0BACAJAADJAQAgCwAAxwEAIAwAAMgBACBnAADVAQAwaAAAAwAQaQAA1QEAMGoEAMABACFrBADAAQAhckAAxQEAIXwBAMEBACF9QADFAQAhgQEBAMIBACEAAAAAAAAFlQEEAAAAAZsBBAAAAAGcAQQAAAABnQEEAAAAAZ4BBAAAAAEBlQEAAABuAgGVASAAAAABAZUBQAAAAAEFlQEEAAAAAZsBBAAAAAGcAQQAAAABnQEEAAAAAZ4BBAAAAAEFGwAAvAMAIBwAAMgDACCSAQAAvQMAIJMBAADHAwAgmAEAAAEAIAUbAAC6AwAgHAAAxQMAIJIBAAC7AwAgkwEAAMQDACCYAQAAAQAgBxsAALgDACAcAADCAwAgkgEAALkDACCTAQAAwQMAIJYBAAADACCXAQAAAwAgmAEAAAUAIAcbAAC2AwAgHAAAvwMAIJIBAAC3AwAgkwEAAL4DACCWAQAABwAglwEAAAcAIJgBAAAJACADGwAAvAMAIJIBAAC9AwAgmAEAAAEAIAMbAAC6AwAgkgEAALsDACCYAQAAAQAgAxsAALgDACCSAQAAuQMAIJgBAAAFACADGwAAtgMAIJIBAAC3AwAgmAEAAAkAIAAAAAAAAZUBAQAAAAEFGwAAqQMAIBwAALQDACCSAQAAqgMAIJMBAACzAwAgmAEAAAUAIAUbAACnAwAgHAAAsQMAIJIBAACoAwAgkwEAALADACCYAQAAAQAgBxsAAKUDACAcAACuAwAgkgEAAKYDACCTAQAArQMAIJYBAAAHACCXAQAABwAgmAEAAAkAIAsbAACAAgAwHAAAhQIAMJIBAACBAgAwkwEAAIICADCUAQAAgwIAIJUBAACEAgAwlgEAAIQCADCXAQAAhAIAMJgBAACEAgAwmQEAAIYCADCaAQAAhwIAMAsbAAD0AQAwHAAA-QEAMJIBAAD1AQAwkwEAAPYBADCUAQAA9wEAIJUBAAD4AQAwlgEAAPgBADCXAQAA-AEAMJgBAAD4AQAwmQEAAPoBADCaAQAA-wEAMAoDAADlAQAgBAAA5wEAIAcAAOYBACBqBAAAAAFrBAAAAAFsBAAAAAFuAAAAbgJvBAAAAAFxIAAAAAFyQAAAAAECAAAADwAgGwAA_wEAIAMAAAAPACAbAAD_AQAgHAAA_gEAIAEUAACsAwAwDwMAAM0BACAEAADSAQAgBwAAzQEAIAgAANMBACBnAADOAQAwaAAADQAQaQAAzgEAMGoEAAAAAWsEAMABACFsBADAAQAhbgAAzwFuIm8EANABACFwBADQAQAhcSAA0QEAIXJAAMUBACECAAAADwAgFAAA_gEAIAIAAAD8AQAgFAAA_QEAIAtnAAD7AQAwaAAA_AEAEGkAAPsBADBqBADAAQAhawQAwAEAIWwEAMABACFuAADPAW4ibwQA0AEAIXAEANABACFxIADRAQAhckAAxQEAIQtnAAD7AQAwaAAA_AEAEGkAAPsBADBqBADAAQAhawQAwAEAIWwEAMABACFuAADPAW4ibwQA0AEAIXAEANABACFxIADRAQAhckAAxQEAIQdqBADcAQAhawQA3AEAIWwEANwBACFuAADdAW4ibwQA4AEAIXEgAN4BACFyQADfAQAhCgMAAOEBACAEAADjAQAgBwAA4gEAIGoEANwBACFrBADcAQAhbAQA3AEAIW4AAN0BbiJvBADgAQAhcSAA3gEAIXJAAN8BACEKAwAA5QEAIAQAAOcBACAHAADmAQAgagQAAAABawQAAAABbAQAAAABbgAAAG4CbwQAAAABcSAAAAABckAAAAABCgMAAI0CACAEAACMAgAgBgAAjgIAIAkAAI8CACBqBAAAAAFrBAAAAAFvBAAAAAFyQAAAAAF8AQAAAAF9QAAAAAECAAAACQAgGwAAiwIAIAMAAAAJACAbAACLAgAgHAAAigIAIAEUAACrAwAwDwMAAM0BACAEAADMAQAgBQAA0wEAIAYAAMcBACAJAADJAQAgZwAA1AEAMGgAAAcAEGkAANQBADBqBAAAAAFrBADAAQAhbwQAwAEAIXJAAMUBACF7BADQAQAhfAEAwQEAIX1AAMUBACECAAAACQAgFAAAigIAIAIAAACIAgAgFAAAiQIAIApnAACHAgAwaAAAiAIAEGkAAIcCADBqBADAAQAhawQAwAEAIW8EAMABACFyQADFAQAhewQA0AEAIXwBAMEBACF9QADFAQAhCmcAAIcCADBoAACIAgAQaQAAhwIAMGoEAMABACFrBADAAQAhbwQAwAEAIXJAAMUBACF7BADQAQAhfAEAwQEAIX1AAMUBACEGagQA3AEAIWsEANwBACFvBADcAQAhckAA3wEAIXwBAO4BACF9QADfAQAhCgMAAPABACAEAADvAQAgBgAA8gEAIAkAAPMBACBqBADcAQAhawQA3AEAIW8EANwBACFyQADfAQAhfAEA7gEAIX1AAN8BACEKAwAAjQIAIAQAAIwCACAGAACOAgAgCQAAjwIAIGoEAAAAAWsEAAAAAW8EAAAAAXJAAAAAAXwBAAAAAX1AAAAAAQMbAACpAwAgkgEAAKoDACCYAQAABQAgAxsAAKcDACCSAQAAqAMAIJgBAAABACAEGwAAgAIAMJIBAACBAgAwlAEAAIMCACCYAQAAhAIAMAQbAAD0AQAwkgEAAPUBADCUAQAA9wEAIJgBAAD4AQAwAxsAAKUDACCSAQAApgMAIJgBAAAJACAAAAAAAAUbAACdAwAgHAAAowMAIJIBAACeAwAgkwEAAKIDACCYAQAABQAgBRsAAJsDACAcAACgAwAgkgEAAJwDACCTAQAAnwMAIJgBAAABACADGwAAnQMAIJIBAACeAwAgmAEAAAUAIAMbAACbAwAgkgEAAJwDACCYAQAAAQAgAAAAAAABlQEBAAAAAQUbAACTAwAgHAAAmQMAIJIBAACUAwAgkwEAAJgDACCYAQAAAQAgCxsAALkCADAcAAC9AgAwkgEAALoCADCTAQAAuwIAMJQBAAC8AgAglQEAAIQCADCWAQAAhAIAMJcBAACEAgAwmAEAAIQCADCZAQAAvgIAMJoBAACHAgAwCxsAAK0CADAcAACyAgAwkgEAAK4CADCTAQAArwIAMJQBAACwAgAglQEAALECADCWAQAAsQIAMJcBAACxAgAwmAEAALECADCZAQAAswIAMJoBAAC0AgAwCxsAAKQCADAcAACoAgAwkgEAAKUCADCTAQAApgIAMJQBAACnAgAglQEAAPgBADCWAQAA-AEAMJcBAAD4AQAwmAEAAPgBADCZAQAAqQIAMJoBAAD7AQAwCgMAAOUBACAHAADmAQAgCAAA6AEAIGoEAAAAAWsEAAAAAWwEAAAAAW4AAABuAnAEAAAAAXEgAAAAAXJAAAAAAQIAAAAPACAbAACsAgAgAwAAAA8AIBsAAKwCACAcAACrAgAgARQAAJcDADACAAAADwAgFAAAqwIAIAIAAAD8AQAgFAAAqgIAIAdqBADcAQAhawQA3AEAIWwEANwBACFuAADdAW4icAQA4AEAIXEgAN4BACFyQADfAQAhCgMAAOEBACAHAADiAQAgCAAA5AEAIGoEANwBACFrBADcAQAhbAQA3AEAIW4AAN0BbiJwBADgAQAhcSAA3gEAIXJAAN8BACEKAwAA5QEAIAcAAOYBACAIAADoAQAgagQAAAABawQAAAABbAQAAAABbgAAAG4CcAQAAAABcSAAAAABckAAAAABBAMAAJkCACBqBAAAAAFrBAAAAAFyQAAAAAECAAAAFwAgGwAAuAIAIAMAAAAXACAbAAC4AgAgHAAAtwIAIAEUAACWAwAwCgMAAM0BACAEAADMAQAgZwAAywEAMGgAABUAEGkAAMsBADBqBAAAAAFrBADAAQAhbwQAwAEAIXJAAMUBACGPAQAAygEAIAIAAAAXACAUAAC3AgAgAgAAALUCACAUAAC2AgAgB2cAALQCADBoAAC1AgAQaQAAtAIAMGoEAMABACFrBADAAQAhbwQAwAEAIXJAAMUBACEHZwAAtAIAMGgAALUCABBpAAC0AgAwagQAwAEAIWsEAMABACFvBADAAQAhckAAxQEAIQNqBADcAQAhawQA3AEAIXJAAN8BACEEAwAAlwIAIGoEANwBACFrBADcAQAhckAA3wEAIQQDAACZAgAgagQAAAABawQAAAABckAAAAABCgMAAI0CACAFAACQAgAgBgAAjgIAIAkAAI8CACBqBAAAAAFrBAAAAAFyQAAAAAF7BAAAAAF8AQAAAAF9QAAAAAECAAAACQAgGwAAwQIAIAMAAAAJACAbAADBAgAgHAAAwAIAIAEUAACVAwAwAgAAAAkAIBQAAMACACACAAAAiAIAIBQAAL8CACAGagQA3AEAIWsEANwBACFyQADfAQAhewQA4AEAIXwBAO4BACF9QADfAQAhCgMAAPABACAFAADxAQAgBgAA8gEAIAkAAPMBACBqBADcAQAhawQA3AEAIXJAAN8BACF7BADgAQAhfAEA7gEAIX1AAN8BACEKAwAAjQIAIAUAAJACACAGAACOAgAgCQAAjwIAIGoEAAAAAWsEAAAAAXJAAAAAAXsEAAAAAXwBAAAAAX1AAAAAAQMbAACTAwAgkgEAAJQDACCYAQAAAQAgBBsAALkCADCSAQAAugIAMJQBAAC8AgAgmAEAAIQCADAEGwAArQIAMJIBAACuAgAwlAEAALACACCYAQAAsQIAMAQbAACkAgAwkgEAAKUCADCUAQAApwIAIJgBAAD4AQAwAAAAAAABlQEAAACJAQIBlQFAAAAAAQsbAAD2AgAwHAAA-wIAMJIBAAD3AgAwkwEAAPgCADCUAQAA-QIAIJUBAAD6AgAwlgEAAPoCADCXAQAA-gIAMJgBAAD6AgAwmQEAAPwCADCaAQAA_QIAMAsbAADtAgAwHAAA8QIAMJIBAADuAgAwkwEAAO8CADCUAQAA8AIAIJUBAACEAgAwlgEAAIQCADCXAQAAhAIAMJgBAACEAgAwmQEAAPICADCaAQAAhwIAMAsbAADkAgAwHAAA6AIAMJIBAADlAgAwkwEAAOYCADCUAQAA5wIAIJUBAACxAgAwlgEAALECADCXAQAAsQIAMJgBAACxAgAwmQEAAOkCADCaAQAAtAIAMAsbAADbAgAwHAAA3wIAMJIBAADcAgAwkwEAAN0CADCUAQAA3gIAIJUBAAD4AQAwlgEAAPgBADCXAQAA-AEAMJgBAAD4AQAwmQEAAOACADCaAQAA-wEAMAsbAADSAgAwHAAA1gIAMJIBAADTAgAwkwEAANQCADCUAQAA1QIAIJUBAAD4AQAwlgEAAPgBADCXAQAA-AEAMJgBAAD4AQAwmQEAANcCADCaAQAA-wEAMAoDAADlAQAgBAAA5wEAIAgAAOgBACBqBAAAAAFrBAAAAAFuAAAAbgJvBAAAAAFwBAAAAAFxIAAAAAFyQAAAAAECAAAADwAgGwAA2gIAIAMAAAAPACAbAADaAgAgHAAA2QIAIAEUAACSAwAwAgAAAA8AIBQAANkCACACAAAA_AEAIBQAANgCACAHagQA3AEAIWsEANwBACFuAADdAW4ibwQA4AEAIXAEAOABACFxIADeAQAhckAA3wEAIQoDAADhAQAgBAAA4wEAIAgAAOQBACBqBADcAQAhawQA3AEAIW4AAN0BbiJvBADgAQAhcAQA4AEAIXEgAN4BACFyQADfAQAhCgMAAOUBACAEAADnAQAgCAAA6AEAIGoEAAAAAWsEAAAAAW4AAABuAm8EAAAAAXAEAAAAAXEgAAAAAXJAAAAAAQoEAADnAQAgBwAA5gEAIAgAAOgBACBqBAAAAAFsBAAAAAFuAAAAbgJvBAAAAAFwBAAAAAFxIAAAAAFyQAAAAAECAAAADwAgGwAA4wIAIAMAAAAPACAbAADjAgAgHAAA4gIAIAEUAACRAwAwAgAAAA8AIBQAAOICACACAAAA_AEAIBQAAOECACAHagQA3AEAIWwEANwBACFuAADdAW4ibwQA4AEAIXAEAOABACFxIADeAQAhckAA3wEAIQoEAADjAQAgBwAA4gEAIAgAAOQBACBqBADcAQAhbAQA3AEAIW4AAN0BbiJvBADgAQAhcAQA4AEAIXEgAN4BACFyQADfAQAhCgQAAOcBACAHAADmAQAgCAAA6AEAIGoEAAAAAWwEAAAAAW4AAABuAm8EAAAAAXAEAAAAAXEgAAAAAXJAAAAAAQQEAACYAgAgagQAAAABbwQAAAABckAAAAABAgAAABcAIBsAAOwCACADAAAAFwAgGwAA7AIAIBwAAOsCACABFAAAkAMAMAIAAAAXACAUAADrAgAgAgAAALUCACAUAADqAgAgA2oEANwBACFvBADcAQAhckAA3wEAIQQEAACWAgAgagQA3AEAIW8EANwBACFyQADfAQAhBAQAAJgCACBqBAAAAAFvBAAAAAFyQAAAAAEKBAAAjAIAIAUAAJACACAGAACOAgAgCQAAjwIAIGoEAAAAAW8EAAAAAXJAAAAAAXsEAAAAAXwBAAAAAX1AAAAAAQIAAAAJACAbAAD1AgAgAwAAAAkAIBsAAPUCACAcAAD0AgAgARQAAI8DADACAAAACQAgFAAA9AIAIAIAAACIAgAgFAAA8wIAIAZqBADcAQAhbwQA3AEAIXJAAN8BACF7BADgAQAhfAEA7gEAIX1AAN8BACEKBAAA7wEAIAUAAPEBACAGAADyAQAgCQAA8wEAIGoEANwBACFvBADcAQAhckAA3wEAIXsEAOABACF8AQDuAQAhfUAA3wEAIQoEAACMAgAgBQAAkAIAIAYAAI4CACAJAACPAgAgagQAAAABbwQAAAABckAAAAABewQAAAABfAEAAAABfUAAAAABCAkAAMUCACALAADDAgAgDAAAxAIAIGoEAAAAAXJAAAAAAXwBAAAAAX1AAAAAAYEBAQAAAAECAAAABQAgGwAAgQMAIAMAAAAFACAbAACBAwAgHAAAgAMAIAEUAACOAwAwDQMAAM0BACAJAADJAQAgCwAAxwEAIAwAAMgBACBnAADVAQAwaAAAAwAQaQAA1QEAMGoEAAAAAWsEAMABACFyQADFAQAhfAEAwQEAIX1AAMUBACGBAQEAwgEAIQIAAAAFACAUAACAAwAgAgAAAP4CACAUAAD_AgAgCWcAAP0CADBoAAD-AgAQaQAA_QIAMGoEAMABACFrBADAAQAhckAAxQEAIXwBAMEBACF9QADFAQAhgQEBAMIBACEJZwAA_QIAMGgAAP4CABBpAAD9AgAwagQAwAEAIWsEAMABACFyQADFAQAhfAEAwQEAIX1AAMUBACGBAQEAwgEAIQVqBADcAQAhckAA3wEAIXwBAO4BACF9QADfAQAhgQEBAJ8CACEICQAAowIAIAsAAKECACAMAACiAgAgagQA3AEAIXJAAN8BACF8AQDuAQAhfUAA3wEAIYEBAQCfAgAhCAkAAMUCACALAADDAgAgDAAAxAIAIGoEAAAAAXJAAAAAAXwBAAAAAX1AAAAAAYEBAQAAAAEEGwAA9gIAMJIBAAD3AgAwlAEAAPkCACCYAQAA-gIAMAQbAADtAgAwkgEAAO4CADCUAQAA8AIAIJgBAACEAgAwBBsAAOQCADCSAQAA5QIAMJQBAADnAgAgmAEAALECADAEGwAA2wIAMJIBAADcAgAwlAEAAN4CACCYAQAA-AEAMAQbAADSAgAwkgEAANMCADCUAQAA1QIAIJgBAAD4AQAwAAAAAAUDAACMAwAgCQAAigMAIAsAAIgDACAMAACJAwAggQEAANYBACAKCQAAigMAIAsAAIgDACAMAACJAwAgDQAAhwMAIA4AAIoDACCFAQAA1gEAIIYBAADWAQAghwEAANYBACCKAQAA1gEAIIsBAADWAQAgBgMAAIwDACAEAACLAwAgBQAAjQMAIAYAAIgDACAJAACKAwAgewAA1gEAIAVqBAAAAAFyQAAAAAF8AQAAAAF9QAAAAAGBAQEAAAABBmoEAAAAAW8EAAAAAXJAAAAAAXsEAAAAAXwBAAAAAX1AAAAAAQNqBAAAAAFvBAAAAAFyQAAAAAEHagQAAAABbAQAAAABbgAAAG4CbwQAAAABcAQAAAABcSAAAAABckAAAAABB2oEAAAAAWsEAAAAAW4AAABuAm8EAAAAAXAEAAAAAXEgAAAAAXJAAAAAARAJAACFAwAgCwAAgwMAIAwAAIQDACAOAACGAwAgagQAAAABckAAAAABfUAAAAABggEBAAAAAYMBAQAAAAGEAQEAAAABhQEBAAAAAYYBAQAAAAGHAQEAAAABiQEAAACJAQKKAQEAAAABiwFAAAAAAQIAAAABACAbAACTAwAgBmoEAAAAAWsEAAAAAXJAAAAAAXsEAAAAAXwBAAAAAX1AAAAAAQNqBAAAAAFrBAAAAAFyQAAAAAEHagQAAAABawQAAAABbAQAAAABbgAAAG4CcAQAAAABcSAAAAABckAAAAABAwAAACcAIBsAAJMDACAcAACaAwAgEgAAACcAIAkAANACACALAADOAgAgDAAAzwIAIA4AANECACAUAACaAwAgagQA3AEAIXJAAN8BACF9QADfAQAhggEBAO4BACGDAQEA7gEAIYQBAQDuAQAhhQEBAJ8CACGGAQEAnwIAIYcBAQCfAgAhiQEAAMsCiQEiigEBAJ8CACGLAUAAzAIAIRAJAADQAgAgCwAAzgIAIAwAAM8CACAOAADRAgAgagQA3AEAIXJAAN8BACF9QADfAQAhggEBAO4BACGDAQEA7gEAIYQBAQDuAQAhhQEBAJ8CACGGAQEAnwIAIYcBAQCfAgAhiQEAAMsCiQEiigEBAJ8CACGLAUAAzAIAIRAJAACFAwAgCwAAgwMAIA0AAIIDACAOAACGAwAgagQAAAABckAAAAABfUAAAAABggEBAAAAAYMBAQAAAAGEAQEAAAABhQEBAAAAAYYBAQAAAAGHAQEAAAABiQEAAACJAQKKAQEAAAABiwFAAAAAAQIAAAABACAbAACbAwAgCQMAAMICACAJAADFAgAgCwAAwwIAIGoEAAAAAWsEAAAAAXJAAAAAAXwBAAAAAX1AAAAAAYEBAQAAAAECAAAABQAgGwAAnQMAIAMAAAAnACAbAACbAwAgHAAAoQMAIBIAAAAnACAJAADQAgAgCwAAzgIAIA0AAM0CACAOAADRAgAgFAAAoQMAIGoEANwBACFyQADfAQAhfUAA3wEAIYIBAQDuAQAhgwEBAO4BACGEAQEA7gEAIYUBAQCfAgAhhgEBAJ8CACGHAQEAnwIAIYkBAADLAokBIooBAQCfAgAhiwFAAMwCACEQCQAA0AIAIAsAAM4CACANAADNAgAgDgAA0QIAIGoEANwBACFyQADfAQAhfUAA3wEAIYIBAQDuAQAhgwEBAO4BACGEAQEA7gEAIYUBAQCfAgAhhgEBAJ8CACGHAQEAnwIAIYkBAADLAokBIooBAQCfAgAhiwFAAMwCACEDAAAAAwAgGwAAnQMAIBwAAKQDACALAAAAAwAgAwAAoAIAIAkAAKMCACALAAChAgAgFAAApAMAIGoEANwBACFrBADcAQAhckAA3wEAIXwBAO4BACF9QADfAQAhgQEBAJ8CACEJAwAAoAIAIAkAAKMCACALAAChAgAgagQA3AEAIWsEANwBACFyQADfAQAhfAEA7gEAIX1AAN8BACGBAQEAnwIAIQsDAACNAgAgBAAAjAIAIAUAAJACACAJAACPAgAgagQAAAABawQAAAABbwQAAAABckAAAAABewQAAAABfAEAAAABfUAAAAABAgAAAAkAIBsAAKUDACAQCQAAhQMAIAwAAIQDACANAACCAwAgDgAAhgMAIGoEAAAAAXJAAAAAAX1AAAAAAYIBAQAAAAGDAQEAAAABhAEBAAAAAYUBAQAAAAGGAQEAAAABhwEBAAAAAYkBAAAAiQECigEBAAAAAYsBQAAAAAECAAAAAQAgGwAApwMAIAkDAADCAgAgCQAAxQIAIAwAAMQCACBqBAAAAAFrBAAAAAFyQAAAAAF8AQAAAAF9QAAAAAGBAQEAAAABAgAAAAUAIBsAAKkDACAGagQAAAABawQAAAABbwQAAAABckAAAAABfAEAAAABfUAAAAABB2oEAAAAAWsEAAAAAWwEAAAAAW4AAABuAm8EAAAAAXEgAAAAAXJAAAAAAQMAAAAHACAbAAClAwAgHAAArwMAIA0AAAAHACADAADwAQAgBAAA7wEAIAUAAPEBACAJAADzAQAgFAAArwMAIGoEANwBACFrBADcAQAhbwQA3AEAIXJAAN8BACF7BADgAQAhfAEA7gEAIX1AAN8BACELAwAA8AEAIAQAAO8BACAFAADxAQAgCQAA8wEAIGoEANwBACFrBADcAQAhbwQA3AEAIXJAAN8BACF7BADgAQAhfAEA7gEAIX1AAN8BACEDAAAAJwAgGwAApwMAIBwAALIDACASAAAAJwAgCQAA0AIAIAwAAM8CACANAADNAgAgDgAA0QIAIBQAALIDACBqBADcAQAhckAA3wEAIX1AAN8BACGCAQEA7gEAIYMBAQDuAQAhhAEBAO4BACGFAQEAnwIAIYYBAQCfAgAhhwEBAJ8CACGJAQAAywKJASKKAQEAnwIAIYsBQADMAgAhEAkAANACACAMAADPAgAgDQAAzQIAIA4AANECACBqBADcAQAhckAA3wEAIX1AAN8BACGCAQEA7gEAIYMBAQDuAQAhhAEBAO4BACGFAQEAnwIAIYYBAQCfAgAhhwEBAJ8CACGJAQAAywKJASKKAQEAnwIAIYsBQADMAgAhAwAAAAMAIBsAAKkDACAcAAC1AwAgCwAAAAMAIAMAAKACACAJAACjAgAgDAAAogIAIBQAALUDACBqBADcAQAhawQA3AEAIXJAAN8BACF8AQDuAQAhfUAA3wEAIYEBAQCfAgAhCQMAAKACACAJAACjAgAgDAAAogIAIGoEANwBACFrBADcAQAhckAA3wEAIXwBAO4BACF9QADfAQAhgQEBAJ8CACELAwAAjQIAIAQAAIwCACAFAACQAgAgBgAAjgIAIGoEAAAAAWsEAAAAAW8EAAAAAXJAAAAAAXsEAAAAAXwBAAAAAX1AAAAAAQIAAAAJACAbAAC2AwAgCQMAAMICACALAADDAgAgDAAAxAIAIGoEAAAAAWsEAAAAAXJAAAAAAXwBAAAAAX1AAAAAAYEBAQAAAAECAAAABQAgGwAAuAMAIBAJAACFAwAgCwAAgwMAIAwAAIQDACANAACCAwAgagQAAAABckAAAAABfUAAAAABggEBAAAAAYMBAQAAAAGEAQEAAAABhQEBAAAAAYYBAQAAAAGHAQEAAAABiQEAAACJAQKKAQEAAAABiwFAAAAAAQIAAAABACAbAAC6AwAgEAsAAIMDACAMAACEAwAgDQAAggMAIA4AAIYDACBqBAAAAAFyQAAAAAF9QAAAAAGCAQEAAAABgwEBAAAAAYQBAQAAAAGFAQEAAAABhgEBAAAAAYcBAQAAAAGJAQAAAIkBAooBAQAAAAGLAUAAAAABAgAAAAEAIBsAALwDACADAAAABwAgGwAAtgMAIBwAAMADACANAAAABwAgAwAA8AEAIAQAAO8BACAFAADxAQAgBgAA8gEAIBQAAMADACBqBADcAQAhawQA3AEAIW8EANwBACFyQADfAQAhewQA4AEAIXwBAO4BACF9QADfAQAhCwMAAPABACAEAADvAQAgBQAA8QEAIAYAAPIBACBqBADcAQAhawQA3AEAIW8EANwBACFyQADfAQAhewQA4AEAIXwBAO4BACF9QADfAQAhAwAAAAMAIBsAALgDACAcAADDAwAgCwAAAAMAIAMAAKACACALAAChAgAgDAAAogIAIBQAAMMDACBqBADcAQAhawQA3AEAIXJAAN8BACF8AQDuAQAhfUAA3wEAIYEBAQCfAgAhCQMAAKACACALAAChAgAgDAAAogIAIGoEANwBACFrBADcAQAhckAA3wEAIXwBAO4BACF9QADfAQAhgQEBAJ8CACEDAAAAJwAgGwAAugMAIBwAAMYDACASAAAAJwAgCQAA0AIAIAsAAM4CACAMAADPAgAgDQAAzQIAIBQAAMYDACBqBADcAQAhckAA3wEAIX1AAN8BACGCAQEA7gEAIYMBAQDuAQAhhAEBAO4BACGFAQEAnwIAIYYBAQCfAgAhhwEBAJ8CACGJAQAAywKJASKKAQEAnwIAIYsBQADMAgAhEAkAANACACALAADOAgAgDAAAzwIAIA0AAM0CACBqBADcAQAhckAA3wEAIX1AAN8BACGCAQEA7gEAIYMBAQDuAQAhhAEBAO4BACGFAQEAnwIAIYYBAQCfAgAhhwEBAJ8CACGJAQAAywKJASKKAQEAnwIAIYsBQADMAgAhAwAAACcAIBsAALwDACAcAADJAwAgEgAAACcAIAsAAM4CACAMAADPAgAgDQAAzQIAIA4AANECACAUAADJAwAgagQA3AEAIXJAAN8BACF9QADfAQAhggEBAO4BACGDAQEA7gEAIYQBAQDuAQAhhQEBAJ8CACGGAQEAnwIAIYcBAQCfAgAhiQEAAMsCiQEiigEBAJ8CACGLAUAAzAIAIRALAADOAgAgDAAAzwIAIA0AAM0CACAOAADRAgAgagQA3AEAIXJAAN8BACF9QADfAQAhggEBAO4BACGDAQEA7gEAIYQBAQDuAQAhhQEBAJ8CACGGAQEAnwIAIYcBAQCfAgAhiQEAAMsCiQEiigEBAJ8CACGLAUAAzAIAIQYJHwQKAAgLHQMMHgYNBgIOIAQFAwABCRkECgAHCwoDDBgGBgMAAQQAAgULAwYMAwkQBAoABQQDAAEEEQIHAAEIEgMCBhMACRQAAgMAAQQAAgMJHAALGgAMGwAFCSQACyIADCMADSEADiUAAAAABQoADSEADiIADyMAECQAEQAAAAAABQoADSEADiIADyMAECQAEQEDAAEBAwABBQoAFiEAFyIAGCMAGSQAGgAAAAAABQoAFiEAFyIAGCMAGSQAGgIDAAEEAAICAwABBAACBQoAHyEAICIAISMAIiQAIwAAAAAABQoAHyEAICIAISMAIiQAIwMDAAEEAAIFcwMDAwABBAACBXkDBQoAKCEAKSIAKiMAKyQALAAAAAAABQoAKCEAKSIAKiMAKyQALAQDAAEEiwECBwABCIwBAwQDAAEEkgECBwABCJMBAwUKADEhADIiADMjADQkADUAAAAAAAUKADEhADIiADMjADQkADUPAgEQJgERKQESKgETKwEVLQEWLwkXMAoYMgEZNAkaNQsdNgEeNwEfOAklOwwmPBInPQIoPgIpPwIqQAIrQQIsQwItRQkuRhMvSAIwSgkxSxQyTAIzTQI0Tgk1URU2Uhs3UwY4VAY5VQY6VgY7VwY8WQY9Wwk-XBw_XgZAYAlBYR1CYgZDYwZEZAlFZx5GaCRHaQNIagNJawNKbANLbQNMbwNNcQlOciVPdQNQdwlReCZSegNTewNUfAlVfydWgAEtV4EBBFiCAQRZgwEEWoQBBFuFAQRchwEEXYkBCV6KAS5fjgEEYJABCWGRAS9ilAEEY5UBBGSWAQllmQEwZpoBNg"
};
async function decodeBase64AsWasm(wasmBase64) {
	const { Buffer } = await import("node:buffer");
	const wasmArray = Buffer.from(wasmBase64, "base64");
	return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
	getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
	getQueryCompilerWasmModule: async () => {
		const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
		return await decodeBase64AsWasm(wasm);
	},
	importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
	return runtime.getPrismaClient(config);
}
runtime.Extensions.getExtensionContext;
runtime.NullTypes.DbNull, runtime.NullTypes.JsonNull, runtime.NullTypes.AnyNull;
runtime.makeStrictEnum({
	ReadUncommitted: "ReadUncommitted",
	ReadCommitted: "ReadCommitted",
	RepeatableRead: "RepeatableRead",
	Serializable: "Serializable"
});
runtime.Extensions.defineExtension;
//#endregion
//#region src/generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
const prisma = new (getPrismaClientClass())({ adapter: new PrismaPg(new Pool({ connectionString: process.env.DATABASE_URL })) });
//#endregion
//#region src/repositories/comment.repository.ts
const baseCommentSelect = {
	id: true,
	post_id: true,
	user_id: true,
	parent_comment_id: true,
	content: true,
	created_at: true,
	updated_at: true,
	user: { select: {
		id: true,
		name: true,
		username: true,
		avatar_url: true
	} }
};
async function findCommentsByPostId(postId, skip, take) {
	return prisma.comment.findMany({
		where: {
			post_id: postId,
			parent_comment_id: null
		},
		select: {
			...baseCommentSelect,
			replies: {
				select: {
					...baseCommentSelect,
					replies: {
						select: {
							...baseCommentSelect,
							_count: { select: { replies: true } }
						},
						orderBy: { created_at: "asc" }
					},
					_count: { select: { replies: true } }
				},
				orderBy: { created_at: "asc" }
			},
			_count: { select: { replies: true } }
		},
		orderBy: { created_at: "desc" },
		skip,
		take
	});
}
async function countRootCommentsByPostId(postId) {
	return prisma.comment.count({ where: {
		post_id: postId,
		parent_comment_id: null
	} });
}
async function findRepliesByCommentId(commentId, skip, take) {
	return prisma.comment.findMany({
		where: { parent_comment_id: commentId },
		select: {
			...baseCommentSelect,
			_count: { select: { replies: true } }
		},
		orderBy: { created_at: "asc" },
		skip,
		take
	});
}
async function countRepliesByCommentId(commentId) {
	return prisma.comment.count({ where: { parent_comment_id: commentId } });
}
async function createComment$1(data) {
	return prisma.comment.create({
		data,
		select: {
			...baseCommentSelect,
			_count: { select: { replies: true } }
		}
	});
}
async function updateComment$1(id, userId, content) {
	const comment = await prisma.comment.findUnique({ where: { id } });
	if (!comment) return null;
	if (comment.user_id !== userId) return "forbidden";
	return prisma.comment.update({
		where: { id },
		data: { content },
		select: {
			...baseCommentSelect,
			_count: { select: { replies: true } }
		}
	});
}
async function deleteComment$1(id, userId) {
	const comment = await prisma.comment.findUnique({ where: { id } });
	if (!comment) return null;
	if (comment.user_id !== userId) return "forbidden";
	await prisma.comment.delete({ where: { id } });
	return true;
}
async function postExists(postId) {
	return !!await prisma.post.findUnique({ where: { id: postId } });
}
async function commentBelongsToPost(commentId, postId) {
	return !!await prisma.comment.findFirst({ where: {
		id: commentId,
		post_id: postId
	} });
}
//#endregion
//#region src/services/comment.service.ts
function serializeBigInt(obj) {
	if (obj === null || obj === void 0) return obj;
	if (typeof obj === "bigint") return obj.toString();
	if (Array.isArray(obj)) return obj.map(serializeBigInt);
	if (typeof obj === "object") return Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, serializeBigInt(v)]));
	return obj;
}
function normalizeComment(comment) {
	const { _count, replies, ...rest } = comment;
	return {
		...rest,
		reply_count: _count?.replies ?? 0,
		replies: Array.isArray(replies) ? replies.map((r) => normalizeComment(r)) : []
	};
}
async function getComments(postId, page, limit) {
	const postBigInt = BigInt(postId);
	if (!await postExists(postBigInt)) return {
		error: "POST_NOT_FOUND",
		status: 404
	};
	const skip = (page - 1) * limit;
	const [comments, total] = await Promise.all([findCommentsByPostId(postBigInt, skip, limit), countRootCommentsByPostId(postBigInt)]);
	return {
		data: serializeBigInt(comments.map((c) => normalizeComment(c))),
		meta: {
			total,
			page,
			limit,
			total_pages: Math.ceil(total / limit),
			has_next: page * limit < total,
			has_prev: page > 1
		}
	};
}
async function getReplies(postId, commentId, page, limit) {
	const postBigInt = BigInt(postId);
	const commentBigInt = BigInt(commentId);
	if (!await postExists(postBigInt)) return {
		error: "POST_NOT_FOUND",
		status: 404
	};
	if (!await commentBelongsToPost(commentBigInt, postBigInt)) return {
		error: "COMMENT_NOT_FOUND",
		status: 404
	};
	const skip = (page - 1) * limit;
	const [replies, total] = await Promise.all([findRepliesByCommentId(commentBigInt, skip, limit), countRepliesByCommentId(commentBigInt)]);
	return {
		data: serializeBigInt(replies.map((r) => normalizeComment(r))),
		meta: {
			total,
			page,
			limit,
			total_pages: Math.ceil(total / limit),
			has_next: page * limit < total,
			has_prev: page > 1
		}
	};
}
async function createComment(postId, body) {
	if (!body.content?.trim()) return {
		error: "CONTENT_REQUIRED",
		status: 422
	};
	const postBigInt = BigInt(postId);
	if (!await postExists(postBigInt)) return {
		error: "POST_NOT_FOUND",
		status: 404
	};
	let parentBigInt;
	if (body.parent_comment_id) {
		parentBigInt = BigInt(body.parent_comment_id);
		if (!await commentBelongsToPost(parentBigInt, postBigInt)) return {
			error: "PARENT_COMMENT_NOT_FOUND",
			status: 404
		};
	}
	return {
		data: serializeBigInt(normalizeComment(await createComment$1({
			post_id: postBigInt,
			user_id: BigInt(body.user_id),
			content: body.content.trim(),
			parent_comment_id: parentBigInt
		}))),
		status: 201
	};
}
async function updateComment(postId, commentId, body) {
	if (!body.content?.trim()) return {
		error: "CONTENT_REQUIRED",
		status: 422
	};
	const postBigInt = BigInt(postId);
	const commentBigInt = BigInt(commentId);
	if (!await commentBelongsToPost(commentBigInt, postBigInt)) return {
		error: "COMMENT_NOT_FOUND",
		status: 404
	};
	const result = await updateComment$1(commentBigInt, BigInt(body.user_id), body.content.trim());
	if (result === null) return {
		error: "COMMENT_NOT_FOUND",
		status: 404
	};
	if (result === "forbidden") return {
		error: "FORBIDDEN",
		status: 403
	};
	return {
		data: serializeBigInt(normalizeComment(result)),
		status: 200
	};
}
async function deleteComment(postId, commentId, userId) {
	const postBigInt = BigInt(postId);
	const commentBigInt = BigInt(commentId);
	if (!await commentBelongsToPost(commentBigInt, postBigInt)) return {
		error: "COMMENT_NOT_FOUND",
		status: 404
	};
	const result = await deleteComment$1(commentBigInt, BigInt(userId));
	if (result === null) return {
		error: "COMMENT_NOT_FOUND",
		status: 404
	};
	if (result === "forbidden") return {
		error: "FORBIDDEN",
		status: 403
	};
	return {
		data: { message: "Comment deleted successfully" },
		status: 200
	};
}
//#endregion
//#region src/routes/comment.routes.ts
const commentRoutes = new Elysia({ prefix: "/posts/:postId/comments" }).get("/", async ({ params, query, set }) => {
	const page = Math.max(1, Number(query.page) || 1);
	const limit = Math.min(50, Math.max(1, Number(query.limit) || 10));
	const result = await getComments(params.postId, page, limit);
	if ("error" in result) {
		set.status = result.status;
		return {
			success: false,
			error: result.error
		};
	}
	return {
		success: true,
		...result
	};
}, {
	params: t.Object({ postId: t.String() }),
	query: t.Object({
		page: t.Optional(t.String()),
		limit: t.Optional(t.String())
	})
}).post("/", async ({ params, body, set }) => {
	const result = await createComment(params.postId, body);
	set.status = result.status ?? 200;
	if ("error" in result) return {
		success: false,
		error: result.error
	};
	return {
		success: true,
		data: result.data
	};
}, {
	params: t.Object({ postId: t.String() }),
	body: t.Object({
		user_id: t.String(),
		content: t.String({ minLength: 1 }),
		parent_comment_id: t.Optional(t.String())
	})
}).get("/:commentId/replies", async ({ params, query, set }) => {
	const page = Math.max(1, Number(query.page) || 1);
	const limit = Math.min(50, Math.max(1, Number(query.limit) || 5));
	const result = await getReplies(params.postId, params.commentId, page, limit);
	if ("error" in result) {
		set.status = result.status;
		return {
			success: false,
			error: result.error
		};
	}
	return {
		success: true,
		...result
	};
}, {
	params: t.Object({
		postId: t.String(),
		commentId: t.String()
	}),
	query: t.Object({
		page: t.Optional(t.String()),
		limit: t.Optional(t.String())
	})
}).patch("/:commentId", async ({ params, body, set }) => {
	const result = await updateComment(params.postId, params.commentId, body);
	set.status = result.status ?? 200;
	if ("error" in result) return {
		success: false,
		error: result.error
	};
	return {
		success: true,
		data: result.data
	};
}, {
	params: t.Object({
		postId: t.String(),
		commentId: t.String()
	}),
	body: t.Object({
		user_id: t.String(),
		content: t.String({ minLength: 1 })
	})
}).delete("/:commentId", async ({ params, body, set }) => {
	const result = await deleteComment(params.postId, params.commentId, body.user_id);
	set.status = result.status ?? 200;
	if ("error" in result) return {
		success: false,
		error: result.error
	};
	return {
		success: true,
		data: result.data
	};
}, {
	params: t.Object({
		postId: t.String(),
		commentId: t.String()
	}),
	body: t.Object({ user_id: t.String() })
});
//#endregion
//#region src/index.ts
dotenv.config();
const app = new Elysia().get("/", () => ({ message: "API is running alias berjalan 🚀 via Lambda Function URL" })).get("/users", ({ query, set }) => {
	const secretKey = query.key;
	if (!secretKey || secretKey !== "asdos-ppwl-rahasia-2026") {
		set.status = 403;
		return {
			success: false,
			error: "FORBIDDEN",
			message: "Akses ditolak! Kunci pemeriksaan salah atau tidak disertakan."
		};
	}
	return [
		{
			id: "1",
			name: "Jesika Manager",
			role: "Admin AWS"
		},
		{
			id: "2",
			name: "Rito Backend",
			role: "Developer"
		},
		{
			id: "3",
			name: "Prilia UI/UX",
			role: "UI/UX Designer"
		}
	];
}).use(commentRoutes).onError(({ code, error, set }) => {
	if (code === "VALIDATION") {
		set.status = 422;
		return {
			success: false,
			error: "VALIDATION_ERROR",
			detail: error.message
		};
	}
	if (code === "NOT_FOUND") {
		set.status = 404;
		return {
			success: false,
			error: "NOT_FOUND"
		};
	}
	console.error("[ERROR]", error);
	set.status = 500;
	return {
		success: false,
		error: "INTERNAL_SERVER_ERROR"
	};
});
const fetch = (request) => app.handle(request);
//#endregion
export { fetch };
